server:
  port: 3045
spring:
  jmx:
    default-domain: FinCluez-Web
  main:
    allow-bean-definition-overriding: true
  jackson:
    default-property-inclusion: NON_NULL
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false     
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
  application:
    name: FinCluez-Web
  banner:
    location: classpath:banner.txt
PROPERTY_PATH: E:/FinCluez/Properties/FinCluez-WebApp.yml
